kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}

          initContainers:
              - name: chmod
                image: alpine:3
                command: 
                  - /bin/sh
                  - -c
                  - 'chmod 770 /data; chown 1001 /data'
                volumeMounts:
                  - name: data
                    mountPath: /data

          containers:
            - name: pgdump
              image: vvang/pgdump:0.5
              command: [ "/bin/bash", "/pgdump.sh" ]
              volumeMounts:
                - name: data
                  mountPath: /data
              env:
                - name: WORKDIR
                  value: /data
                - name: PGHOST
                  value: {{ .Values.pghost }}
                - name: PGPORT
                  value: {{ .Values.pgport | quote }}
                - name: PGUSER
                  value: {{ .Values.pguser }}
                - name: PGPASSWORD
                  valueFrom: 
                    secretKeyRef:
                      name: {{ .Values.secret_pgpass }}
                      key: {{ .Values.secret_key }}

