apiVersion: v1
entries:
  pgdump:
  - apiVersion: v2
    appVersion: "0.7"
    created: "2025-12-09T18:48:22.185598+02:00"
    description: A Helm chart for pgdump (postgresql dumps) in Kubernetes
    digest: c56757a63212fff2cbb4f637d31826e4bb338a667b4d77f430fd1aefcf5bd302
    name: pgdump
    type: application
    urls:
    - pgdump-0.3.0.tgz
    version: 0.3.0
generated: "2025-12-09T18:48:22.184603+02:00"
